class Names:
    DBNAME = 'ASE_PROJ'
    SERVER_CONNECT = 'mongodb://localhost:27017/'

    DB_DATA_COLLECTION = 'FILES'
    DB_ACTION_COLLECTION = 'ACTIONS'

    DB_DATA_COLLECTION_PATH = '_id'
    DB_DATA_COLLECTION_SIGN = 'SIGN'
    DB_DATA_COLLECTION_CONFIG = 'CONFIG_ID'
    DB_DATA_COLLECTION_TYPE = 'TYPE'
    # DB_DATA_COLLECTION_ACTION = 'ACTION_ID'
    DB_DATA_COLLECTION_OWNER = 'OWNER_USER'
    DB_DATA_COLLECTION_PARENT_OWNER = 'PARENT_OWNER'

    DB_CONFIGS_FLAG = [
        'READ_ONLY',
        'FULL_SCAN',
        'NON_SCAN',
        'SYSTEM_FILE',
        'EXE',
        'HIDDEN_FILE'
    ]

    DB_ACTION_COLLECTION_BY = 'BY_USER'
    DB_ACTION_COLLECTION_TYPE = 'TYPE'
    DB_ACTION_COLLECTION_TIME = 'TIME'
    DB_ACTION_COLLECTION_ISVALID = 'ISVALID'
    DB_ACTION_COLLECTION_PATH = 'FILEPATH'
