class Names:

    DB_HOME = 'DBFiles'
    PATHFILE = 'DBFiles/PATH.txt'
    DB_DATA_COLLECTION = 'FILES.csv'
    DB_ACTION_COLLECTION = 'ACTIONS.csv'

    DB_DATA_FIELDS = ['_id', 'SIGN', 'CONFIG_ID',
                      'TYPE', 'OWNER_USER', 'PARENT_OWNER', ]

    DB_DATA_COLLECTION_PATH = 0
    DB_DATA_COLLECTION_SIGN = 1
    DB_DATA_COLLECTION_CONFIG = 2
    DB_DATA_COLLECTION_TYPE = 3
    DB_DATA_COLLECTION_OWNER = 4
    DB_DATA_COLLECTION_PARENT_OWNER = 5

    DB_CONFIGS_FLAG = [
        'READ_ONLY',
        'FULL_SCAN',
        'NON_SCAN',
        'SYSTEM_FILE',
        'EXE',
        'HIDDEN_FILE'
    ]

    DB_ACTION_FIELDS = ['BY_USER', 'TYPE', 'TIME', 'ISVALID', 'FILEPATH', ]

    DB_ACTION_COLLECTION_BY = 0
    DB_ACTION_COLLECTION_TYPE = 1
    DB_ACTION_COLLECTION_TIME = 2
    DB_ACTION_COLLECTION_ISVALID = 3
    DB_ACTION_COLLECTION_PATH = 4
